// Code generated by protoc-gen-go. DO NOT EDIT.
// source: foo.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	foo.proto

It has these top-level messages:
	FooRequest
	FooResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FooRequest struct {
}

func (m *FooRequest) Reset()                    { *m = FooRequest{} }
func (m *FooRequest) String() string            { return proto.CompactTextString(m) }
func (*FooRequest) ProtoMessage()               {}
func (*FooRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FooResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *FooResponse) Reset()                    { *m = FooResponse{} }
func (m *FooResponse) String() string            { return proto.CompactTextString(m) }
func (*FooResponse) ProtoMessage()               {}
func (*FooResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FooResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*FooRequest)(nil), "grpc.FooRequest")
	proto.RegisterType((*FooResponse)(nil), "grpc.FooResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Foo service

type FooClient interface {
	GetFoo(ctx context.Context, in *FooRequest, opts ...grpc1.CallOption) (*FooResponse, error)
}

type fooClient struct {
	cc *grpc1.ClientConn
}

func NewFooClient(cc *grpc1.ClientConn) FooClient {
	return &fooClient{cc}
}

func (c *fooClient) GetFoo(ctx context.Context, in *FooRequest, opts ...grpc1.CallOption) (*FooResponse, error) {
	out := new(FooResponse)
	err := grpc1.Invoke(ctx, "/grpc.Foo/GetFoo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Foo service

type FooServer interface {
	GetFoo(context.Context, *FooRequest) (*FooResponse, error)
}

func RegisterFooServer(s *grpc1.Server, srv FooServer) {
	s.RegisterService(&_Foo_serviceDesc, srv)
}

func _Foo_GetFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServer).GetFoo(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Foo/GetFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServer).GetFoo(ctx, req.(*FooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Foo_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Foo",
	HandlerType: (*FooServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "GetFoo",
			Handler:    _Foo_GetFoo_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "foo.proto",
}

func init() { proto.RegisterFile("foo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xcb, 0xcf, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0xe2, 0xe1, 0xe2, 0x72,
	0xcb, 0xcf, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x52, 0xe4, 0xe2, 0x06, 0xf3, 0x8a,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x23, 0x33, 0x2e, 0x66, 0xb7, 0xfc, 0x7c, 0x21, 0x7d, 0x2e,
	0x36, 0xf7, 0xd4, 0x12, 0x10, 0x4b, 0x40, 0x0f, 0x64, 0x90, 0x1e, 0xc2, 0x14, 0x29, 0x41, 0x24,
	0x11, 0x88, 0x49, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x5b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x88, 0xc8, 0xc1, 0x86, 0x82, 0x00, 0x00, 0x00,
}
